"""no blank project name

Revision ID: 2a090b83d8ac
Revises: e0c0bcba40cb
Create Date: 2024-02-28 13:29:59.443057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a090b83d8ac"
down_revision: Union[str, None] = "e0c0bcba40cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Project", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "name_is_not_empty", sa.func.length(sa.func.trim(sa.column("name"))) > 0
        )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Project", schema=None) as batch_op:
        batch_op.drop_constraint("name_is_not_empty", type_="check")
    pass
    # ### end Alembic commands ###
