"""add is active flags to all relevant models

Revision ID: 3606fe990453
Revises: f23a6909ffd6
Create Date: 2024-03-05 09:34:14.865324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3606fe990453'
down_revision: Union[str, None] = 'f23a6909ffd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('Event', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
