"""Add forgotten name field

Revision ID: d1c8fc4b8ab4
Revises: f46712611c85
Create Date: 2024-02-21 20:39:44.385247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c8fc4b8ab4'
down_revision: Union[str, None] = 'f46712611c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_Task_name'), ['name'], unique=False)
        batch_op.create_unique_constraint('unique_task', ['project_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.drop_constraint('unique_task', type_='unique')
        batch_op.drop_index(batch_op.f('ix_Task_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
