"""no empty names

Revision ID: e0c0bcba40cb
Revises: 45f2a027037b
Create Date: 2024-02-28 13:17:03.199828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0c0bcba40cb"
down_revision: Union[str, None] = "45f2a027037b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Task", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "no_empty_names", sa.func.length(sa.func.trim(sa.column("name"))) > 0
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Task", schema=None) as batch_op:
        batch_op.drop_constraint("no_empty_names", type_="check")
    # ### end Alembic commands ###
