"""Fix foreignkeys to cascade delete

Revision ID: f23a6909ffd6
Revises: 2a090b83d8ac
Create Date: 2024-03-01 12:16:53.281547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f23a6909ffd6"
down_revision: Union[str, None] = "2a090b83d8ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Entry", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_entry_event", "Event", ["event_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("Event", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_event_task", "Task", ["task_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("Project", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_project_client", "Client", ["client_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("Task", schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "fK_task_project", "Project", ["project_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Task", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "Project", ["project_id"], ["id"])

    with op.batch_alter_table("Project", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "Client", ["client_id"], ["id"])

    with op.batch_alter_table("Event", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "Task", ["task_id"], ["id"])

    with op.batch_alter_table("Entry", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "Event", ["event_id"], ["id"])

    # ### end Alembic commands ###
