"""simplify stop reasons

Revision ID: f46712611c85
Revises: 864bfaf7a2f7
Create Date: 2024-02-21 20:21:59.947018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46712611c85'
down_revision: Union[str, None] = '864bfaf7a2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entry', schema=None) as batch_op:
        batch_op.alter_column('stop_reason',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('PAUSED', 'FINISHED', name='stopreasons'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entry', schema=None) as batch_op:
        batch_op.alter_column('stop_reason',
               existing_type=sa.Enum('PAUSED', 'FINISHED', name='stopreasons'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
