"""actually add is active to entry

Revision ID: fcb5fea1955c
Revises: cdbb1c1c6e59
Create Date: 2024-03-06 09:20:29.317143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb5fea1955c'
down_revision: Union[str, None] = 'cdbb1c1c6e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Entry', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
